### ISSUE TITLE
Vite's sourcemap plugin doesn't work

### ISSUE THREAD

**Issue by Andarist** [filipsobol/sonda#6]
1. Repro: https://github.com/Andarist/unplugin-sourcemaps-issue
2. run `yarn && yarn start` to start the app
3. open devtools
4. refresh the app

You might see the *app code* sourcemapped. The call stack might also look fairly OK since it uses mapped function names from React. However, when I click on those frames I'm presented the `index.html` content instead of the React's JS source code.

Note that to get app code sourcemapped I had use this configuration:
```ts
  build: {
    sourcemap: true,
  },
```

Based on the docs alone, I assumed that this would be auto-configured for me.

**Comment by filipsobol** [comment]
React's source maps don't include the `sourcesContent` so the final source map produced by Vite is missing React sources too.

This should be fixed by #9. Please try the patch from this comment and let me know if it addresses this issue: https://github.com/filipsobol/sonda/pull/9#issuecomment-2402840766.

I also updated README.md to include missing information about enabling source maps.

**Comment by filipsobol** [comment]
Fixed in `unplugin-sourcemaps@0.1.2`
